POST http://localhost:9000/2015-03-31/functions/function/invocations HTTP/1.1
content-type: application/json

{
    "method": "POST",
    "body": "{\"sketch\":\"void leaphyProgram() {\\n}\\n\\n\\nvoid setup() {\\n  leaphyProgram();\\n}\\n\\nvoid loop() {\\n\\n}\"}",
    "mode": "cors",
    "redirect": "follow",
    "headers": {
        "content-type": "application/json"
    }
}